### PR TITLE
Async and MQTT is comming :P

### LINKED ISSUE #113: Integration slow to setup (on HA start)
The integrations takes more then 25 seconds to setup correctly.

Comparing to other integrations, which take only a few seconds to setup up (normally under 2 seconds, except the mobile app which takes 10 seconds for 10 devices).

The problem is probably, that we poll all statuses directly in the main thread. We should create a task to do that in the background, this will also make the UI setup quicker.

### LINKED ISSUE #118: Problem with livemap
I just installed your integration few days ago, and first of all, a big thank you! The official Ecovacs integration is strangely abandoned, so thank you very much for your efforts!

**Describe the bug**
From time to time, the livemap image does not look OK, it seems really oversized, with the actual map shrinked in the bottom left corner of the image.

**Configuration.yaml (Remember to delete your credentials)**
N/A (config flow now)
**Screenshots**
livemap

**System Informations:**
 - Device: DEEBOT OZMO T8+
## System Health

version | core-2021.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | Europe/Brussels

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4890
Installed Version | 1.12.3
Stage | running
Available Repositories | 820
Installed Repositories | 32

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 19.03.15
disk_total | 62.3 GB
disk_used | 31.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), File editor (5.3.0), Check Home Assistant configuration (3.7.1), SSH & Web Terminal (8.2.1), Visual Studio Code (3.3.1), SONOS AudioClip TTS (2.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 17
views | 8
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Additional context**
It may got fixed (normal map gets back), but then it reappears. 

**Logs**
Does not seem useful, but let me know otherwise.

### LINKED ISSUE #127: Reduce the amount of requests - Polling
Hi @And3rsL 

I read other threads about polling issues but they are closed (apprently fixed in 2.1.1).

Sadly I reach 15'000 polling in 24h to portla-na.ecouser.net still with 2.1.1. I own 2 Ecovacs T9, map is disabled.  

Do I need to adjust something?

### PR DESCRIPTION
**Pull request by edenhaus**
A lot of refactoring....
The whole library was be rewritten to support asyncio, mqtt (reducing polling) and a lot more

Implements the changes from https://github.com/And3rsL/Deebotozmo/pull/29

Also fixes #118, fixes #113, fixes #127

### CODE REVIEW

**Comment by illivanillie** [comment]
Keep us updated! 👍 
love your work guys, wish I could contribute

**Comment by edenhaus** [comment]
> Keep us updated! +1
> love your work guys, wish I could contribute

You can always contribute :) If you can't write code, you can still test it and give us feedback.
I will release probably next week a pre-rerelease

**Comment by illivanillie** [comment]
I’ll be the first one to test it.
Any chance that #82 will be manageable? My workaround is a non-workaround now

**Comment by edenhaus** [comment]
> I’ll be the first one to test it.
> Any chance that #82 will be manageable? My workaround is a non-workaround now

The pre-release is out. About #82 I will give it a look next week, I need some logs to find out, what information the robots is providing

**Comment by illivanillie** [comment]
How can I install it? Via HACS? What was the config again?

**Comment by edenhaus** [comment]
> How can I install it? Via HACS? What was the config again?

You can install it via Hacs if you enable beta versions. They config is the same as for 2.1.1 it will be migrated automatically

**Comment by edenhaus** [comment]
@And3rsL Can you please give it a look and also test it. If nothing is found, I would suggest we will release it soon :) This PR is already big and I don’t want to add new features to it

**Comment by And3rsL** [comment]
> @And3rsL Can you please give it a look and also test it. If nothing is found, I would suggest we will release it soon :) This PR is already big and I don’t want to add new features to it

i was testing b6 and looks good so far. i will let run b8 for a few days

anyway i agree with you we should release it and see!
You have done a great job!

**Comment by edenhaus** [comment]
I will give it a look. I don't use the maps and therefore I didn't notice it.

For the clean logs, I probably need your help as bumper is not supporting it yet...

**Comment by And3rsL** [comment]
Its very stable , we can release when you are ready

**Comment by edenhaus** [comment]
> Its very stable , we can release when you are ready

I have released today a new beta, with status polling. I would wait a couple of days and then release it, if nothing happens.

**Comment by edenhaus** [comment]
@And3rsL I released 3.0.0b12 a few moments ago. I would test this one until Wednesday and if nothing big was found, release it on next friday

**Pull request merged**
