### PR TITLE
add an advanced ui example

### PR DESCRIPTION
**Pull request by edenhaus**
After @aidbish shared his UI (Thanks for that) I got the request from my family if it is possible to control the order in which way the rooms are cleaned.
It took me some hours to find a working solution, which I want to share it with you.
If someone has a better idea, how to store the order (`variable.deebot_susi_queue`). Please feel to comment :)

Currently my UI looks like:
ui-advanced

### CODE REVIEW

**Comment by Maxtropos** [comment]
I'm, doing quite the same via Node-Red. I use an array for buffering the rooms. I call the cleaning commands with only a single room, then wait for the bot state to change to docking and then passing the next room via a new cleaning command. Docking the bot manually empties the queue. This has the advantage, that I can add rooms on the fly (especially when using Aquara Opple Switches to do so). I don't know, if this is possible with hassio scripting alone, I only "code" with NodeRed.

**Comment by edenhaus** [comment]
> I'm, doing quite the same via Node-Red. I use an array for buffering the rooms. I call the cleaning commands with only a single room, then wait for the bot state to change to docking and then passing the next room via a new cleaning command. Docking the bot manually empties the queue. This has the advantage, that I can add rooms on the fly (especially when using Aquara Opple Switches to do so). I don't know, if this is possible with hassio scripting alone, I only "code" with NodeRed.

Yes it is also possible directly in HA.

The disadvantage of your suggestion is, that you create a seperate job for each room and therefore the last cleaning image is only about that room and not all rooms. I use the image to check if the robot has cleaned all rooms correctly. Sometime it happen, that a door was closed or something else... With my solution I see all room on one image.

But you are welcome to share your setup 😊 Maybe someone need exactly this one. One example could be if you have motion sensor in each room and you want only add it to the queue if nobody is in the room

**Review by And3rsL — APPROVED** [review]

**Comment by Maxtropos** [comment]
> The disadvantage of your suggestion is, that you create a seperate job for each room and therefore the last cleaning image is only about that room and not all rooms. I use the image to check if the robot has cleaned all rooms correctly. Sometime it happen, that a door was closed or something else... With my solution I see all room on one image.
> 

That's probably right. I almost never use the cleaning image, so I never thought about this issue.
```
[{"id":"e8ca32b.350c7d","type":"function","z":"1ca70639.02b64a","name":"Queue catch","func":"if (msg.queue[0] == undefined) return [null, msg];\nelse {\nmsg.nachsterraum = msg.queue[0];\nfor (i=0; msg.queue[i] != undefined ;i++){  \nmsg.queue[i]= msg.queue[i+1];\n}\nreturn [msg, null];\n}","outputs":2,"noerr":0,"initialize":"","finalize":"","libs":[],"x":2010,"y":4140,"wires":[["7a331c43.e1d784"],[]]},{"id":"936b8ae7.d34a18","type":"server-events","z":"1ca70639.02b64a","name":"","server":"62bd7c3c.e8e914","version":1,"event_type":"walleraum","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"waitForRunning":true,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"}],"x":1630,"y":4060,"wires":[["817c8141.370e6"]]},{"id":"d57ba157.e4a8e","type":"function","z":"1ca70639.02b64a","name":"Queue add","func":"if (msg.queue[0] == null) {\n    msg.queue[0]= msg.payload.event\n    return [msg];\n}\n\nfor (i=9; msg.queue[i] == null ;i--){ \n    if (msg.queue[i-1] != null){\nmsg.queue[i]= msg.payload.event\nreturn [msg];\n    }}\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":2050,"y":4060,"wires":[["87c02561.09c038"]]},{"id":"1aa84d72.44b923","type":"change","z":"1ca70639.02b64a","name":"Queue löschen","rules":[{"t":"set","p":"queue","pt":"flow","to":"[null,null,null,null,null,null,null,null,null,null]","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":1960,"y":3940,"wires":[[]]},{"id":"cd55d9f2.30ba68","type":"inject","z":"1ca70639.02b64a","name":"Restart","props":[{"p":"queue","v":"[null,null,null,null,null,null,null,null,null,null]","vt":"json"}],"repeat":"","crontab":"","once":true,"onceDelay":"5","topic":"","x":1780,"y":3940,"wires":[["1aa84d72.44b923"]]},{"id":"9b438b10.374408","type":"change","z":"1ca70639.02b64a","name":"","rules":[{"t":"set","p":"queue","pt":"msg","to":"queue","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":1830,"y":4140,"wires":[["e8ca32b.350c7d"]]},{"id":"7a331c43.e1d784","type":"change","z":"1ca70639.02b64a","name":"","rules":[{"t":"set","p":"queue","pt":"flow","to":"queue","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":2230,"y":4120,"wires":[["a4a4321.154f9d"]]},{"id":"817c8141.370e6","type":"change","z":"1ca70639.02b64a","name":"","rules":[{"t":"set","p":"queue","pt":"msg","to":"queue","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":1850,"y":4060,"wires":[["d57ba157.e4a8e"]]},{"id":"87c02561.09c038","type":"change","z":"1ca70639.02b64a","name":"","rules":[{"t":"set","p":"queue","pt":"flow","to":"queue","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":2230,"y":4060,"wires":[["50e53e40.e8957","48e3ef66.f8b54"]]},{"id":"81f3ca1b.15c3a8","type":"server-events","z":"1ca70639.02b64a","name":"Call Service","server":"62bd7c3c.e8e914","version":1,"event_type":"call_service","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"waitForRunning":true,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"eventData"}],"x":1610,"y":3980,"wires":[["2f1d094b.7f3346"]]},{"id":"2f1d094b.7f3346","type":"switch","z":"1ca70639.02b64a","name":"Return to base?","property":"payload.event.service","propertyType":"msg","rules":[{"t":"eq","v":"return_to_base","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":1840,"y":3980,"wires":[["1aa84d72.44b923"]]},{"id":"d99d215.f682ee","type":"server-state-changed","z":"1ca70639.02b64a","name":"Walle dockt","server":"62bd7c3c.e8e914","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"vacuum.wall_e","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"returning","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":"2","forType":"num","forUnits":"seconds","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":1610,"y":4140,"wires":[["9b438b10.374408"],[]]},{"id":"a4a4321.154f9d","type":"api-call-service","z":"1ca70639.02b64a","name":"Wall-E FanSpeed","server":"62bd7c3c.e8e914","version":3,"debugenabled":false,"service_domain":"vacuum","service":"set_fan_speed","entityId":"vacuum.wall_e","data":"{\"fan_speed\":\"{{nachsterraum.stufe}}\"}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":2430,"y":4120,"wires":[["e129ee1e.9b689"]]},{"id":"e9d2d3c8.29b7e","type":"switch","z":"1ca70639.02b64a","name":"Raum/Zone?","property":"msg.nachsterraum.typ","propertyType":"msg","rules":[{"t":"eq","v":"raum","vt":"str"},{"t":"eq","v":"zone","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":2970,"y":4120,"wires":[["49c401ea.6bc29"],["525f8102.11163"]]},{"id":"e129ee1e.9b689","type":"api-call-service","z":"1ca70639.02b64a","name":"Wall-E CleanCounts","server":"62bd7c3c.e8e914","version":3,"debugenabled":false,"service_domain":"vacuum","service":"send_command","entityId":"vacuum.wall_e","data":"{    \"command\": \"setCleanCount\",    \"params\": {        \"count\": {{nachsterraum.anz}}    }}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":2640,"y":4120,"wires":[["ddc81eec.c8032"]]},{"id":"525f8102.11163","type":"api-call-service","z":"1ca70639.02b64a","name":"Wall-E Los","server":"62bd7c3c.e8e914","version":3,"debugenabled":false,"service_domain":"vacuum","service":"send_command","entityId":"vacuum.wall_e","data":"{\"command\":\"custom_area\",\"params\":{\"coordinates\":\"{{nachsterraum.raum}}\"}}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":3130,"y":4160,"wires":[[]]},{"id":"49c401ea.6bc29","type":"api-call-service","z":"1ca70639.02b64a","name":"Wall-E Los","server":"62bd7c3c.e8e914","version":3,"debugenabled":true,"service_domain":"vacuum","service":"send_command","entityId":"vacuum.wall_e","data":"{\"command\":\"spot_area\",\"params\":{\"rooms\":\"{{nachsterraum.raum}}\"}}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":3150,"y":4100,"wires":[[]]},{"id":"48e3ef66.f8b54","type":"api-current-state","z":"1ca70639.02b64a","name":"Docked?","server":"62bd7c3c.e8e914","version":2,"outputs":2,"halt_if":"docked","halt_if_type":"str","halt_if_compare":"is","entity_id":"vacuum.wall_e","state_type":"str","blockInputOverrides":false,"outputProperties":[],"override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":2400,"y":4060,"wires":[["9b438b10.374408"],[]]},{"id":"50e53e40.e8957","type":"api-current-state","z":"1ca70639.02b64a","name":"Returning","server":"62bd7c3c.e8e914","version":2,"outputs":2,"halt_if":"returning","halt_if_type":"str","halt_if_compare":"is","entity_id":"vacuum.wall_e","state_type":"str","blockInputOverrides":false,"outputProperties":[],"override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":2400,"y":4020,"wires":[["9b438b10.374408"],[]]},{"id":"b29d91d9.c1d38","type":"server-state-changed","z":"1ca70639.02b64a","name":"Walle angedockt","server":"62bd7c3c.e8e914","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"vacuum.wall_e","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"docked","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":"2","forType":"num","forUnits":"seconds","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":1620,"y":4180,"wires":[["9b438b10.374408"],[]]},{"id":"ddc81eec.c8032","type":"delay","z":"1ca70639.02b64a","name":"2s","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":2810,"y":4120,"wires":[["e9d2d3c8.29b7e"]]},{"id":"62bd7c3c.e8e914","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":false,"cacheJson":true}]
```

Adding to the queue works by triggering an event "walleraum" (My vac is called Wall-E) and sending them:
```
typ: raum (raum for room / zone for custom zone)
raum: '{{ states.vacuum.wall_e.attributes.room_bathroom}}' (Room ID/custom zone coordinates)
anz: 1 (cleaning 1x or 2x)
stufe: normal (fan setting in plain text)
```

**Comment by edenhaus** [comment]
@Maxtropos Can you please create a seperate file, where you describe your note red example a little bit more and probably with a screenshot?

Only if you want to share it 😊

**Comment by Maxtropos** [comment]
> @Maxtropos Can you please create a seperate file, where you describe your note red example a little bit more and probably with a screenshot?
> 
> Only if you want to share it 😊
 
#172

**Pull request merged**
