### PR TITLE
add version to manifest and workflow to set it

### PR DESCRIPTION
**Pull request by edenhaus**
Addedrequired version field to manifest and add a workflow to set it automatically.
Copied from https://github.com/custom-components/authenticated/pull/66

Fixes https://github.com/And3rsL/Deebot-for-hassio/issues/80

@And3rsL Can you please add the environment variable `secrets.GITHUB_TOKEN` as I don't have the permissions to add it.

### CODE REVIEW

**Comment by And3rsL** [comment]
i currently have big changes pending such as native interface integration instead of via configuration.yaml
i will include this pr asap

**Comment by edenhaus** [comment]
@And3rsL 
I can help you if you want :) or at least testing it.
The best would be to create a separate branch and push it, so I can give you feedback

**Comment by And3rsL** [comment]
> > i currently have big changes pending such as native interface integration instead of via configuration.yaml
> > i will include this pr asap
> 
> @And3rsL I can help you if you want :) or at least testing it.
> The best would be to create a separate branch and push it, so I can give you feedback

just published it in the beta branch

it should fixed #77 , #69 , #31 and in general all configuration.yaml mistakes made from users

**Comment by edenhaus** [comment]
@And3rsL I change the code to meet with the new code base. Also the target is the beta branch.
So if you create `secrets.GITHUB_TOKEN` variable, you can merge it to the beta branch :)

**Review by And3rsL — APPROVED** [review]

**Pull request merged**
